server.port=8085
logging.level.gmdev=INFO
spring.data.mongodb.database=AlertViewer
files.path=/opt/lv/csv
ingest.fixedrate=30000
ingester.type=alertmanager
management.endpoints.web.exposure.include=prometheus
initial.days.ago=5

security.require-ssl=true
login.username=user
login.password=p_ssword1

spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost

wraith.generic.url=http://localhost:5000/generic
testmode.enabled=false

