server.port=8085
logging.level.dts=DEBUG
spring.data.mongodb.database=LogViewer
files.path=/opt/lv/csv
ingest.fixedrate=30000
ingester.type=alertmanager
management.endpoints.web.exposure.include=prometheus
initial.days.ago=5

spring.profiles.active=dev

server.ssl.key-store-type=JKS
server.ssl.key-store=/opt/certs/keystore.jks
server.ssl.key-store-password=p_ssword1
server.ssl.key-alias=tomcat

security.require-ssl=true
login.username=user
login.password=p_ssword1

